FROM node:24

ARG GO_VERSION=1.26.0

WORKDIR /workspace

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential \
    ca-certificates \
    lsb-release \
    postgresql \
    && rm -rf /var/lib/apt/lists/*

RUN npm install vite

ENV PATH="/usr/local/go/bin:${PATH}"
